/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#00174b',
        'tertiary-fixed-dim': '#ffb596',
        'outline-variant': '#c3c6d7',
        'surface-container-highest': '#e0e3e5',
        'primary': '#004ac6',
        'tertiary-container': '#bc4800',
        'on-surface': '#191c1e',
        'surface-container-high': '#e6e8ea',
        'on-surface-variant': '#434655',
        'surface': '#f7f9fb',
        'surface-variant': '#e0e3e5',
        'secondary': '#495c95',
        'on-background': '#191c1e',
        'on-tertiary': '#ffffff',
        'surface-dim': '#d8dadc',
        'secondary-fixed-dim': '#b4c5ff',
        'outline': '#737686',
        'primary-fixed': '#dbe1ff',
        'on-error': '#ffffff',
        'background': '#f7f9fb',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary-fixed': '#360f00',
        'on-primary-container': '#eeefff',
        'inverse-primary': '#b4c5ff',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f7f9fb',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-primary-fixed-variant': '#003ea8',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#31447b',
        'on-secondary-fixed': '#00174b',
        'on-secondary-container': '#394c84',
        'primary-container': '#2563eb',
        'surface-container': '#eceef0',
        'secondary-fixed': '#dbe1ff',
        'on-error-container': '#93000a',
        'secondary-container': '#acbfff',
        'tertiary': '#943700',
        'on-tertiary-container': '#ffede6',
        'surface-tint': '#0053db',
        'error-container': '#ffdad6',
        'inverse-surface': '#2d3133',
        'tertiary-fixed': '#ffdbcd',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'primary-fixed-dim': '#b4c5ff',
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
