# Generated by Django 6.0.4 on 2026-04-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
